// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBphy88VbdH-cS4LJOmlMc3wggzRLcMxmE',
    appId: '1:815714525839:web:46cea23508ef17ddef86fa',
    messagingSenderId: '815714525839',
    projectId: 'vouchee-504da',
    authDomain: 'vouchee-504da.firebaseapp.com',
    storageBucket: 'vouchee-504da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwki-hDhBWPEJlzb-6Hd59gyx7vX7Hu0',
    appId: '1:815714525839:android:91a1559a4630dd89ef86fa',
    messagingSenderId: '815714525839',
    projectId: 'vouchee-504da',
    storageBucket: 'vouchee-504da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPssHEliBxFoYa3DCqIwVU_C2HsvYYWgQ',
    appId: '1:815714525839:ios:0bd4b816b88c36e1ef86fa',
    messagingSenderId: '815714525839',
    projectId: 'vouchee-504da',
    storageBucket: 'vouchee-504da.appspot.com',
    androidClientId: '815714525839-41aqgtq0i4db39s2tejbnikjce8ram25.apps.googleusercontent.com',
    iosClientId: '815714525839-r9fq8dhm74cmpcho8g0cffop0g1s6783.apps.googleusercontent.com',
    iosBundleId: 'com.example.vouchee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPssHEliBxFoYa3DCqIwVU_C2HsvYYWgQ',
    appId: '1:815714525839:ios:0bd4b816b88c36e1ef86fa',
    messagingSenderId: '815714525839',
    projectId: 'vouchee-504da',
    storageBucket: 'vouchee-504da.appspot.com',
    androidClientId: '815714525839-41aqgtq0i4db39s2tejbnikjce8ram25.apps.googleusercontent.com',
    iosClientId: '815714525839-r9fq8dhm74cmpcho8g0cffop0g1s6783.apps.googleusercontent.com',
    iosBundleId: 'com.example.vouchee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvmoWs28y4eQdX5KRINfb3bEkasEexQFY',
    appId: '1:815714525839:web:6eb3399385994094ef86fa',
    messagingSenderId: '815714525839',
    projectId: 'vouchee-504da',
    authDomain: 'vouchee-504da.firebaseapp.com',
    storageBucket: 'vouchee-504da.appspot.com',
  );

}